---
# yaml-language-server: $schema=https://raw.githubusercontent.com/reubenmiller/go-c8y-cli/master/tools/schema/session.schema.json
settings:
  activitylog:
    path: "~/.cumulocity/activitylog"
    enabled: true
  session:
    defaultUsername: ''
  defaults: {}
  template:
    path: "$C8Y_HOME/templates"
  views:
    commonPaths:
    - "$C8Y_HOME/views/default"
    - "~/.config/c8y/views"
    columnMinWidth: 5
    columnMaxWidth: 80
    columnPadding: 5
  commonAliases:
    recentAlarms: alarms list --dateFrom -1h
    mo: inventory get --view off --output json --id '$1'
